
services:

  nats:
    image: nats-streaming:latest
    expose:
      - 4222
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: "supet1337"
      POSTGRES_PASSWORD: "Asdfgh12345"
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migration/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    ports:
      - "5432:5432"